version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_HOST_PORT:-80}:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./node-service
    ports:
      - "${BACKEND_HOST_PORT:-3000}:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/mydatabase
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: mongo:latest
    # No host port exposure; backend reaches via service name in internal network
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
